### ISSUE TITLE
Throw an error if cssnext is used with default options not as the first plugin

### ISSUE THREAD

**Issue by MoOx** [MoOx/cssnext#175]
Some people include cssnext after other plugins, but since cssnext handle import by default, it should be the first so, if possible:

- if cssnext has default options || import to true && import hasn't been piped yet, should throw if not the first plugin
- if cssnext has default options || import to true && import has already been piped, should disable import (& should emit a warning ?) if not the first plugin
- if cssnext has import to false, just check nothing, people probably know what they are doing

That would avoid people doing mistake.

**Comment by jedmao** [comment]
I have nested and nested-props running on each import, which is why I also have nested and nested props running before cssnext. Basically, I don't want it trying to unwrap nested syntax more than once for the same code, so it unwraps nesting on the non-imported code first, then unwraps nesting on each import as they come.

**Comment by MoOx** [comment]
What you are asking will be doable with this option #149

**Comment by jedmao** [comment]
Thanks! I'll follow that thread.

**Comment by MoOx** [comment]
Useless now that (postcss-)cssnext doesn't handle import anymore.
